name: freezed_practices
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'




dependencies:
  json_annotation: 
  meta: 

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner:
  freezed: 
  json_serializable: 
